const object_definitions = {
    channels: {
        type: 'channel',
        common: {
            name: 'Channels',
        },
        native: {},
    },
    'channels.channel': {
        type: 'channel',
        common: {
            name: 'Channel',
        },
        native: {},
    },
    'channels.channel.alarm': {
        type: 'state',
        common: {
            name: 'Alarm activated',
            role: 'state',
            type: 'boolean',
            unit: '',
            write: false,
            read: true,
        },
        native: {},
    },
    'channels.channel.color': {
        type: 'state',
        common: {
            name: 'Color',
            role: 'state',
            type: 'string',
            unit: '',
            write: false,
            read: true,
        },
        native: {},
    },
    'channels.channel.connected': {
        type: 'state',
        common: {
            name: 'Connected',
            role: 'state',
            type: 'boolean',
            unit: '',
            write: false,
            read: true,
        },
        native: {},
    },
    'channels.channel.fixed': {
        type: 'state',
        common: {
            name: 'Fixed',
            role: 'state',
            type: 'boolean',
            unit: '',
            write: false,
            read: true,
        },
        native: {},
    },
    'channels.channel.max': {
        type: 'state',
        common: {
            name: 'Max. temperature',
            role: 'state',
            type: 'number',
            unit: '',
            write: false,
            read: true,
        },
        native: {},
    },
    'channels.channel.min': {
        type: 'state',
        common: {
            name: 'Min. temperature',
            role: 'state',
            type: 'number',
            unit: '',
            write: false,
            read: true,
        },
        native: {},
    },
    'channels.channel.name': {
        type: 'state',
        common: {
            name: 'Name',
            role: 'state',
            type: 'string',
            unit: '',
            write: false,
            read: true,
        },
        native: {},
    },
    'channels.channel.number': {
        type: 'state',
        common: {
            name: 'Number',
            role: 'state',
            type: 'number',
            unit: '',
            write: false,
            read: true,
        },
        native: {},
    },
    'channels.channel.temp': {
        type: 'state',
        common: {
            name: 'Temperature',
            role: 'state',
            type: 'number',
            unit: '',
            write: false,
            read: true,
        },
        native: {},
    },
    'channels.channel.type': {
        type: 'state',
        common: {
            name: 'Type',
            role: 'state',
            type: 'number',
            unit: '',
            write: false,
            read: true,
        },
        native: {},
    },
    system: {
        type: 'channel',
        common: {
            name: 'System info',
        },
        native: {},
    },
    'system.charge': {
        type: 'state',
        common: {
            name: 'Charging',
            role: 'state',
            type: 'boolean',
            unit: '',
            write: false,
            read: true,
        },
        native: {},
    },
    'system.online': {
        type: 'state',
        common: {
            name: 'Online',
            role: 'state',
            type: 'number',
            unit: '',
            write: false,
            read: true,
        },
        native: {},
    },
    'system.rssi': {
        type: 'state',
        common: {
            name: 'RSSI',
            role: 'state',
            type: 'number',
            unit: '',
            write: false,
            read: true,
        },
        native: {},
    },
    'system.soc': {
        type: 'state',
        common: {
            name: 'Soc',
            role: 'state',
            type: 'number',
            unit: '',
            write: false,
            read: true,
        },
        native: {},
    },
    'system.time': {
        type: 'state',
        common: {
            name: 'Time',
            role: 'state',
            type: 'number',
            unit: '',
            write: false,
            read: true,
        },
        native: {},
    },
    'system.unit': {
        type: 'state',
        common: {
            name: 'Unit',
            role: 'state',
            type: 'string',
            unit: '',
            write: false,
            read: true,
        },
        native: {},
    },
};

module.exports = { defObj: object_definitions };
